# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 The Linux Foundation
"""Tests for scripts/review-command.sh.

Each composed command line is parsed twice: by a port of the splitter
Gerrit's SSH daemon applies to it, and by a real POSIX shell. Hostile
messages must come back from both as one literal --message argument
and must never run anything.
"""

from __future__ import annotations

import os
import subprocess
import tempfile
import unittest
from pathlib import Path

SCRIPT = Path(__file__).resolve().parent.parent / "scripts" / "review-command.sh"
RUN_URL = "https://github.com/example/repo/actions/runs/42"
MAX_MESSAGE_BYTES = 4096
TAG = ["--tag", "autogenerated:github"]

# Each would create a file named 'pwned' if any part of it ran.
HOSTILE_MESSAGES = [
    "it's",
    "'",
    "''''",
    "'; touch pwned; echo '",
    '"; touch pwned; echo "',
    "$(touch pwned)",
    "`touch pwned`",
    "; touch pwned",
    "a && touch pwned || true",
    "a | touch pwned",
    "> pwned",
    "\\",
    "trailing backslash \\",
    "\\'; touch pwned #",
    "back\\slash \\' \\\" \\\\",
    "first line\n'; touch pwned; '\n$(touch pwned)",
    "--label Code-Review=+2",
    "' --label Code-Review=+2 '",
    "$HOME ${PATH} * ? [a] ~ # ! %",
    'mixed "double" \'single\' "\'"\'"',
    "Unicode — ✓ ünïcödé 🚀",
]


def gerrit_split(command_line: str) -> list[str]:
    """Split a command line as Gerrit's SSH daemon does.

    A port of CommandFactoryProvider.split():
    https://gerrit.googlesource.com/gerrit/+/refs/heads/master/java/com/google/gerrit/sshd/CommandFactoryProvider.java
    """
    words: list[str] = []
    word: list[str] = []
    in_single = in_double = False
    i = 0
    while i < len(command_line):
        char = command_line[i]
        i += 1
        if char in " \t":
            if in_single or in_double:
                word.append(char)
            elif word:
                words.append("".join(word))
                word = []
        elif char == '"':
            if in_single:
                word.append(char)
            else:
                in_double = not in_double
        elif char == "'":
            if in_double:
                word.append(char)
            else:
                in_single = not in_single
        elif char == "\\":
            if in_single or i == len(command_line):
                word.append(char)
            else:
                word.append(command_line[i])
                i += 1
        else:
            word.append(char)
    if word:
        words.append("".join(word))
    return words


def shell_split(command_line: str, cwd: str) -> list[str]:
    """Return the words a POSIX shell parses from command_line."""
    result = subprocess.run(
        ["sh", "-c", f"set -- {command_line}\nprintf '%s\\0' \"$@\""],
        cwd=cwd,
        capture_output=True,
        check=True,
    )
    return result.stdout.decode("utf-8").split("\0")[:-1]


def compose(
    message: str | None = None, **overrides: str
) -> subprocess.CompletedProcess[str]:
    """Run the script with valid defaults, overridden per test."""
    env = {
        "PATH": os.environ["PATH"],
        "VOTE_TYPE": "success",
        "COMMENT_ONLY": "false",
        "GERRIT_CHANGE_NUMBER": "123",
        "GERRIT_PATCHSET_NUMBER": "4",
        "RUN_URL": RUN_URL,
    }
    if message is not None:
        env["REVIEW_MESSAGE"] = message
    env.update(overrides)
    return subprocess.run(
        [str(SCRIPT)],
        env=env,
        capture_output=True,
        encoding="utf-8",
        check=False,
    )


class GerritSplitTest(unittest.TestCase):
    """The port reproduces Gerrit's documented splitting rules."""

    def test_rules(self) -> None:
        cases = {
            "a  b\tc": ["a", "b", "c"],
            "'a b' \"c d\"": ["a b", "c d"],
            "'a\"b' \"a'b\"": ['a"b', "a'b"],
            "a\\ b \\'": ["a b", "'"],
            "'a\\b' end\\": ["a\\b", "end\\"],
            "'' x": ["x"],
            "'a\nb'": ["a\nb"],
        }
        for line, expected in cases.items():
            with self.subTest(line=line):
                self.assertEqual(gerrit_split(line), expected)


class ComposeTest(unittest.TestCase):
    """Comment composition, votes and input validation."""

    def assert_review(
        self, result: subprocess.CompletedProcess[str], comment: str, labels: list[str]
    ) -> None:
        self.assertEqual(result.returncode, 0, result.stderr)
        argv = gerrit_split(result.stdout.rstrip("\n"))
        expected = ["gerrit", "review", "123,4", "--message", comment, *labels, *TAG]
        self.assertEqual(argv, expected)

    def assert_rejected(self, result: subprocess.CompletedProcess[str]) -> None:
        self.assertNotEqual(result.returncode, 0)
        self.assertEqual(result.stdout, "")
        self.assertIn("::error::", result.stderr)

    def test_unset_message_keeps_existing_command(self) -> None:
        result = compose()
        self.assertEqual(
            result.stdout,
            f"gerrit review 123,4 --message 'SUCCESS: {RUN_URL}' "
            "--label Verified=1 --tag autogenerated:github\n",
        )

    def test_empty_message_matches_unset(self) -> None:
        self.assertEqual(compose("").stdout, compose().stdout)
        self.assertEqual(compose("\n\n").stdout, compose().stdout)

    def test_vote_types(self) -> None:
        cases = {
            "clear": ("STARTED", ["Verified=0", "Code-Review=0"]),
            "success": ("SUCCESS", ["Verified=1"]),
            "failure": ("FAILURE", ["Verified=-1"]),
            "cancelled": ("CANCELLED", ["Verified=-1", "Code-Review=-1"]),
        }
        for vote_type, (status, votes) in cases.items():
            labels = [arg for vote in votes for arg in ("--label", vote)]
            with self.subTest(vote_type=vote_type):
                self.assert_review(
                    compose(VOTE_TYPE=vote_type), f"{status}: {RUN_URL}", labels
                )

    def test_comment_only_omits_labels(self) -> None:
        self.assert_review(compose(COMMENT_ONLY="true"), f"SUCCESS: {RUN_URL}", [])

    def test_message_appended(self) -> None:
        self.assert_review(
            compose("Released 1.1.1 to nexus."),
            f"SUCCESS: {RUN_URL}\n\nReleased 1.1.1 to nexus.",
            ["--label", "Verified=1"],
        )

    def test_multiline_message_keeps_inner_newlines(self) -> None:
        message = "Snapshot 1.1.2-SNAPSHOT published to nexus.\n\nNo release file.\n"
        self.assert_review(
            compose(message),
            f"SUCCESS: {RUN_URL}\n\n{message.rstrip()}",
            ["--label", "Verified=1"],
        )

    def test_hostile_messages_stay_literal(self) -> None:
        for message in HOSTILE_MESSAGES:
            with self.subTest(message=message):
                result = compose(message, COMMENT_ONLY="true")
                comment = f"SUCCESS: {RUN_URL}\n\n{message}"
                self.assert_review(result, comment, [])
                with tempfile.TemporaryDirectory() as cwd:
                    # A file for an unquoted glob to expand to
                    Path(cwd, "a").touch()
                    argv = shell_split(result.stdout.rstrip("\n"), cwd)
                    self.assertFalse(Path(cwd, "pwned").exists())
                self.assertEqual(
                    argv, ["gerrit", "review", "123,4", "--message", comment, *TAG]
                )

    def test_length_cap_counts_bytes(self) -> None:
        self.assertEqual(compose("a" * MAX_MESSAGE_BYTES).returncode, 0)
        self.assert_rejected(compose("a" * (MAX_MESSAGE_BYTES + 1)))
        # 'é' is two bytes in UTF-8
        self.assertEqual(compose("é" * (MAX_MESSAGE_BYTES // 2)).returncode, 0)
        self.assert_rejected(compose("é" * (MAX_MESSAGE_BYTES // 2 + 1)))

    def test_control_characters_rejected(self) -> None:
        # NUL cannot reach the script: an environment value ends at it.
        controls = [chr(c) for c in range(1, 32) if c != 10]
        controls += ["\x7f", "\x80", "\x85", "\x9b", "\x9f"]
        for char in controls:
            with self.subTest(char=hex(ord(char))):
                result = compose(f"before{char}after")
                self.assert_rejected(result)
                self.assertNotIn("before", result.stderr)

    def test_invalid_inputs_rejected(self) -> None:
        cases = [
            {"VOTE_TYPE": "approve"},
            {"VOTE_TYPE": ""},
            {"GERRIT_CHANGE_NUMBER": "0"},
            {"GERRIT_CHANGE_NUMBER": "012"},
            {"GERRIT_CHANGE_NUMBER": "1; id"},
            {"GERRIT_PATCHSET_NUMBER": "1 --label Code-Review=+2"},
            {"GERRIT_PATCHSET_NUMBER": ""},
        ]
        for overrides in cases:
            with self.subTest(overrides=overrides):
                self.assert_rejected(compose(**overrides))


if __name__ == "__main__":
    unittest.main()
