#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2026 The Linux Foundation

# Print the 'gerrit review' command line the action sends over SSH.
#
# Reads its inputs from the environment, so the calling step never
# interpolates a templated value into shell code:
#
#   VOTE_TYPE               clear, success, failure or cancelled
#   COMMENT_ONLY            'false' applies the votes; any other value
#                           posts the comment alone
#   GERRIT_CHANGE_NUMBER    positive integer
#   GERRIT_PATCHSET_NUMBER  positive integer
#   RUN_URL                 link back to the workflow run
#   REVIEW_MESSAGE          optional text appended to the comment
#
# The comment is '<STATUS>: <RUN_URL>', followed by a blank line and
# REVIEW_MESSAGE when that is set. REVIEW_MESSAGE is capped at
# MAX_MESSAGE_BYTES and may hold newlines but no other control
# characters; anything else exits non-zero and prints nothing on
# stdout.
#
# ssh joins its arguments into one string, and Gerrit's SSH daemon
# splits that string again (CommandFactoryProvider.split): blanks
# separate words, quotes group them, and a backslash outside single
# quotes escapes the next character. It expands nothing. The comment
# travels as a single single-quoted word, with each embedded single
# quote written as '\'' (close, escaped quote, reopen). A POSIX shell
# reads that form identically, so the word stays literal whichever of
# the two parses it.

set -euo pipefail
# Byte semantics: the length cap counts bytes and the character
# checks below match single bytes.
export LC_ALL=C

readonly MAX_MESSAGE_BYTES=4096

fail() {
  # Never echo the message itself: it is caller-supplied, and the
  # runner would act on any workflow command embedded in it.
  echo "::error::$*" >&2
  exit 1
}

# Wrap one argument in single quotes for the remote command line.
quote() {
  local escaped="'\\''"
  printf "'%s'" "${1//\'/${escaped}}"
}

case "${VOTE_TYPE:-}" in
  clear)
    labels="--label Verified=0 --label Code-Review=0"
    status="STARTED"
    ;;
  success)
    labels="--label Verified=1"
    status="SUCCESS"
    ;;
  failure)
    labels="--label Verified=-1"
    status="FAILURE"
    ;;
  cancelled)
    labels="--label Verified=-1 --label Code-Review=-1"
    status="CANCELLED"
    ;;
  *)
    fail "Unknown vote-type '${VOTE_TYPE:-}':" \
      "expected clear, success, failure or cancelled"
    ;;
esac

# Positive integers only (no leading zeros), so whitespace or
# metacharacters cannot change the meaning of the remote command.
change="${GERRIT_CHANGE_NUMBER:-}"
patchset="${GERRIT_PATCHSET_NUMBER:-}"
if [[ ! "${change}" =~ ^[1-9][0-9]*$ ]]; then
  fail "Refusing to use gerrit-change-number '${change}':" \
    "must be a positive integer"
fi
if [[ ! "${patchset}" =~ ^[1-9][0-9]*$ ]]; then
  fail "Refusing to use gerrit-patchset-number '${patchset}':" \
    "must be a positive integer"
fi

message="${REVIEW_MESSAGE:-}"
if (( ${#message} > MAX_MESSAGE_BYTES )); then
  fail "Refusing to use message: ${#message} bytes exceeds the" \
    "${MAX_MESSAGE_BYTES}-byte limit"
fi
# Newline is the one control character a message may carry. Tab, CR,
# escape sequences and the rest could disguise the comment in Gerrit
# or in the run log. C1 controls (U+0080-U+009F) are the UTF-8 byte
# pairs 0xC2 0x80-0x9F.
c1_lead=$'\xc2'
c1_range=$'[\x80-\x9f]'
if [[ "${message//$'\n'/}" == *[[:cntrl:]]* ]] \
  || [[ "${message}" == *"${c1_lead}"${c1_range}* ]]; then
  fail "Refusing to use message: it contains a control character" \
    "other than newline"
fi
# A YAML block scalar ('message: |') ends in a newline; drop those.
while [[ "${message}" == *$'\n' ]]; do
  message="${message%$'\n'}"
done

comment="${status}: ${RUN_URL:-}"
if [[ -n "${message}" ]]; then
  comment+=$'\n\n'"${message}"
fi

review="gerrit review ${change},${patchset} --message $(quote "${comment}")"
if [[ "${COMMENT_ONLY:-}" == "false" ]]; then
  review+=" ${labels}"
fi
review+=" --tag autogenerated:github"
printf '%s\n' "${review}"
